package com.ximuyi.demo.mybatis.model;

import java.io.Serializable;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

public class Bill implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bill.Id
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bill.Name
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bill.Approach
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private String approach;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bill.Date
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bill.Caculate
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private Double caculate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bill.Amount
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private Double amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bill.Received
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private Double received;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bill.Remain
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private Double remain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bill.Goods
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private String goods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bill.Comment
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bill.Delete
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private Integer delete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Bill
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Bill
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private Map<String, Boolean> selectiveColumns = new HashMap<String, Boolean>();

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bill.Id
     *
     * @return the value of Bill.Id
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bill.Id
     *
     * @param id the value for Bill.Id
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bill.Name
     *
     * @return the value of Bill.Name
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bill.Name
     *
     * @param name the value for Bill.Name
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bill.Approach
     *
     * @return the value of Bill.Approach
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public String getApproach() {
        return approach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bill.Approach
     *
     * @param approach the value for Bill.Approach
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setApproach(String approach) {
        this.approach = approach == null ? null : approach.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bill.Date
     *
     * @return the value of Bill.Date
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bill.Date
     *
     * @param date the value for Bill.Date
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bill.Caculate
     *
     * @return the value of Bill.Caculate
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public Double getCaculate() {
        return caculate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bill.Caculate
     *
     * @param caculate the value for Bill.Caculate
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setCaculate(Double caculate) {
        this.caculate = caculate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bill.Amount
     *
     * @return the value of Bill.Amount
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bill.Amount
     *
     * @param amount the value for Bill.Amount
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bill.Received
     *
     * @return the value of Bill.Received
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public Double getReceived() {
        return received;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bill.Received
     *
     * @param received the value for Bill.Received
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setReceived(Double received) {
        this.received = received;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bill.Remain
     *
     * @return the value of Bill.Remain
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public Double getRemain() {
        return remain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bill.Remain
     *
     * @param remain the value for Bill.Remain
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setRemain(Double remain) {
        this.remain = remain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bill.Goods
     *
     * @return the value of Bill.Goods
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public String getGoods() {
        return goods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bill.Goods
     *
     * @param goods the value for Bill.Goods
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setGoods(String goods) {
        this.goods = goods == null ? null : goods.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bill.Comment
     *
     * @return the value of Bill.Comment
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bill.Comment
     *
     * @param comment the value for Bill.Comment
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bill.Delete
     *
     * @return the value of Bill.Delete
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public Integer getDelete() {
        return delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bill.Delete
     *
     * @param delete the value for Bill.Delete
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setDelete(Integer delete) {
        this.delete = delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bill
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static Bill.Builder builder() {
        return new Bill.Builder();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bill
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public boolean hasSelective() {
        return this.selectiveColumns.size() > 0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bill
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public boolean hasSelective(String column) {
        return this.selectiveColumns.get(column) != null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bill
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Bill selective(Column ... columns) {
        this.selectiveColumns.clear();
        if (columns != null) {
            for (Column column : columns) {
                this.selectiveColumns.put(column.value(), true);
            }
        }
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Bill
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table Bill
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private Bill obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Bill
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new Bill();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Bill.Id
         *
         * @param id the value for Bill.Id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder id(Long id) {
            obj.setId(id);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Bill.Name
         *
         * @param name the value for Bill.Name
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder name(String name) {
            obj.setName(name);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Bill.Approach
         *
         * @param approach the value for Bill.Approach
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder approach(String approach) {
            obj.setApproach(approach);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Bill.Date
         *
         * @param date the value for Bill.Date
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder date(Date date) {
            obj.setDate(date);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Bill.Caculate
         *
         * @param caculate the value for Bill.Caculate
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder caculate(Double caculate) {
            obj.setCaculate(caculate);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Bill.Amount
         *
         * @param amount the value for Bill.Amount
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder amount(Double amount) {
            obj.setAmount(amount);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Bill.Received
         *
         * @param received the value for Bill.Received
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder received(Double received) {
            obj.setReceived(received);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Bill.Remain
         *
         * @param remain the value for Bill.Remain
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder remain(Double remain) {
            obj.setRemain(remain);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Bill.Goods
         *
         * @param goods the value for Bill.Goods
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder goods(String goods) {
            obj.setGoods(goods);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Bill.Comment
         *
         * @param comment the value for Bill.Comment
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder comment(String comment) {
            obj.setComment(comment);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Bill.Delete
         *
         * @param delete the value for Bill.Delete
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder delete(Integer delete) {
            obj.setDelete(delete);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Bill
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Bill build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table Bill
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("Id"),
        name("Name"),
        approach("Approach"),
        date("Date"),
        caculate("Caculate"),
        amount("Amount"),
        received("Received"),
        remain("Remain"),
        goods("Goods"),
        comment("Comment"),
        delete("Delete");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table Bill
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Bill
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Bill
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Bill
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Bill
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Bill
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}