package com.ximuyi.demo.mybatis.model;

import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;

public class Idgen implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IdGen.IdType
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private Integer idtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IdGen.CurrentId
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private Long currentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table IdGen
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table IdGen
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private Map<String, Boolean> selectiveColumns = new HashMap<String, Boolean>();

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IdGen.IdType
     *
     * @return the value of IdGen.IdType
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public Integer getIdtype() {
        return idtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IdGen.IdType
     *
     * @param idtype the value for IdGen.IdType
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setIdtype(Integer idtype) {
        this.idtype = idtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IdGen.CurrentId
     *
     * @return the value of IdGen.CurrentId
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public Long getCurrentid() {
        return currentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IdGen.CurrentId
     *
     * @param currentid the value for IdGen.CurrentId
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setCurrentid(Long currentid) {
        this.currentid = currentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IdGen
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static Idgen.Builder builder() {
        return new Idgen.Builder();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IdGen
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public boolean hasSelective() {
        return this.selectiveColumns.size() > 0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IdGen
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public boolean hasSelective(String column) {
        return this.selectiveColumns.get(column) != null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IdGen
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Idgen selective(Column ... columns) {
        this.selectiveColumns.clear();
        if (columns != null) {
            for (Column column : columns) {
                this.selectiveColumns.put(column.value(), true);
            }
        }
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table IdGen
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table IdGen
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private Idgen obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table IdGen
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new Idgen();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column IdGen.IdType
         *
         * @param idtype the value for IdGen.IdType
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder idtype(Integer idtype) {
            obj.setIdtype(idtype);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column IdGen.CurrentId
         *
         * @param currentid the value for IdGen.CurrentId
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder currentid(Long currentid) {
            obj.setCurrentid(currentid);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table IdGen
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Idgen build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table IdGen
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        idtype("IdType"),
        currentid("CurrentId");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table IdGen
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table IdGen
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table IdGen
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table IdGen
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table IdGen
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table IdGen
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}