package com.ximuyi.demo.mybatis.model;

import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;

public class Stock implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Stock.Id
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Stock.Name
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Stock.Type
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Stock.Num
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Stock.Unit
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Stock.GetPrice
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private Double getprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Stock.SalePrice
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private Double saleprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Stock.NoticeNum
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private Integer noticenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Stock.Vender
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private String vender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Stock.Comment
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Stock.Delete
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private Integer delete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Stock
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Stock
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private Map<String, Boolean> selectiveColumns = new HashMap<String, Boolean>();

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Stock.Id
     *
     * @return the value of Stock.Id
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Stock.Id
     *
     * @param id the value for Stock.Id
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Stock.Name
     *
     * @return the value of Stock.Name
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Stock.Name
     *
     * @param name the value for Stock.Name
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Stock.Type
     *
     * @return the value of Stock.Type
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Stock.Type
     *
     * @param type the value for Stock.Type
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Stock.Num
     *
     * @return the value of Stock.Num
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Stock.Num
     *
     * @param num the value for Stock.Num
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Stock.Unit
     *
     * @return the value of Stock.Unit
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Stock.Unit
     *
     * @param unit the value for Stock.Unit
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Stock.GetPrice
     *
     * @return the value of Stock.GetPrice
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public Double getGetprice() {
        return getprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Stock.GetPrice
     *
     * @param getprice the value for Stock.GetPrice
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setGetprice(Double getprice) {
        this.getprice = getprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Stock.SalePrice
     *
     * @return the value of Stock.SalePrice
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public Double getSaleprice() {
        return saleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Stock.SalePrice
     *
     * @param saleprice the value for Stock.SalePrice
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setSaleprice(Double saleprice) {
        this.saleprice = saleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Stock.NoticeNum
     *
     * @return the value of Stock.NoticeNum
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public Integer getNoticenum() {
        return noticenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Stock.NoticeNum
     *
     * @param noticenum the value for Stock.NoticeNum
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setNoticenum(Integer noticenum) {
        this.noticenum = noticenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Stock.Vender
     *
     * @return the value of Stock.Vender
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public String getVender() {
        return vender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Stock.Vender
     *
     * @param vender the value for Stock.Vender
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setVender(String vender) {
        this.vender = vender == null ? null : vender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Stock.Comment
     *
     * @return the value of Stock.Comment
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Stock.Comment
     *
     * @param comment the value for Stock.Comment
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Stock.Delete
     *
     * @return the value of Stock.Delete
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public Integer getDelete() {
        return delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Stock.Delete
     *
     * @param delete the value for Stock.Delete
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setDelete(Integer delete) {
        this.delete = delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Stock
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static Stock.Builder builder() {
        return new Stock.Builder();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Stock
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public boolean hasSelective() {
        return this.selectiveColumns.size() > 0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Stock
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public boolean hasSelective(String column) {
        return this.selectiveColumns.get(column) != null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Stock
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Stock selective(Column ... columns) {
        this.selectiveColumns.clear();
        if (columns != null) {
            for (Column column : columns) {
                this.selectiveColumns.put(column.value(), true);
            }
        }
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Stock
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table Stock
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private Stock obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Stock
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new Stock();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Stock.Id
         *
         * @param id the value for Stock.Id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder id(Long id) {
            obj.setId(id);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Stock.Name
         *
         * @param name the value for Stock.Name
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder name(String name) {
            obj.setName(name);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Stock.Type
         *
         * @param type the value for Stock.Type
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder type(String type) {
            obj.setType(type);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Stock.Num
         *
         * @param num the value for Stock.Num
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder num(Integer num) {
            obj.setNum(num);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Stock.Unit
         *
         * @param unit the value for Stock.Unit
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder unit(String unit) {
            obj.setUnit(unit);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Stock.GetPrice
         *
         * @param getprice the value for Stock.GetPrice
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder getprice(Double getprice) {
            obj.setGetprice(getprice);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Stock.SalePrice
         *
         * @param saleprice the value for Stock.SalePrice
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder saleprice(Double saleprice) {
            obj.setSaleprice(saleprice);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Stock.NoticeNum
         *
         * @param noticenum the value for Stock.NoticeNum
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder noticenum(Integer noticenum) {
            obj.setNoticenum(noticenum);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Stock.Vender
         *
         * @param vender the value for Stock.Vender
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder vender(String vender) {
            obj.setVender(vender);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Stock.Comment
         *
         * @param comment the value for Stock.Comment
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder comment(String comment) {
            obj.setComment(comment);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Stock.Delete
         *
         * @param delete the value for Stock.Delete
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder delete(Integer delete) {
            obj.setDelete(delete);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Stock
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Stock build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table Stock
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("Id"),
        name("Name"),
        type("Type"),
        num("Num"),
        unit("Unit"),
        getprice("GetPrice"),
        saleprice("SalePrice"),
        noticenum("NoticeNum"),
        vender("Vender"),
        comment("Comment"),
        delete("Delete");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table Stock
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Stock
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Stock
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Stock
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Stock
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Stock
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}