package com.ximuyi.demo.mybatis.model;

import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;

public class Supplier implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Supplier.Id
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Supplier.Name
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Supplier.Phone
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Supplier.Address
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Supplier.Comment
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Supplier.Delete
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private Integer delete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Supplier
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Supplier
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private Map<String, Boolean> selectiveColumns = new HashMap<String, Boolean>();

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Supplier.Id
     *
     * @return the value of Supplier.Id
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Supplier.Id
     *
     * @param id the value for Supplier.Id
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Supplier.Name
     *
     * @return the value of Supplier.Name
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Supplier.Name
     *
     * @param name the value for Supplier.Name
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Supplier.Phone
     *
     * @return the value of Supplier.Phone
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Supplier.Phone
     *
     * @param phone the value for Supplier.Phone
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Supplier.Address
     *
     * @return the value of Supplier.Address
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Supplier.Address
     *
     * @param address the value for Supplier.Address
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Supplier.Comment
     *
     * @return the value of Supplier.Comment
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Supplier.Comment
     *
     * @param comment the value for Supplier.Comment
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Supplier.Delete
     *
     * @return the value of Supplier.Delete
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public Integer getDelete() {
        return delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Supplier.Delete
     *
     * @param delete the value for Supplier.Delete
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setDelete(Integer delete) {
        this.delete = delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Supplier
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static Supplier.Builder builder() {
        return new Supplier.Builder();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Supplier
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public boolean hasSelective() {
        return this.selectiveColumns.size() > 0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Supplier
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public boolean hasSelective(String column) {
        return this.selectiveColumns.get(column) != null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Supplier
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Supplier selective(Column ... columns) {
        this.selectiveColumns.clear();
        if (columns != null) {
            for (Column column : columns) {
                this.selectiveColumns.put(column.value(), true);
            }
        }
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Supplier
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table Supplier
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private Supplier obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Supplier
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new Supplier();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Supplier.Id
         *
         * @param id the value for Supplier.Id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder id(Long id) {
            obj.setId(id);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Supplier.Name
         *
         * @param name the value for Supplier.Name
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder name(String name) {
            obj.setName(name);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Supplier.Phone
         *
         * @param phone the value for Supplier.Phone
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder phone(String phone) {
            obj.setPhone(phone);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Supplier.Address
         *
         * @param address the value for Supplier.Address
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder address(String address) {
            obj.setAddress(address);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Supplier.Comment
         *
         * @param comment the value for Supplier.Comment
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder comment(String comment) {
            obj.setComment(comment);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Supplier.Delete
         *
         * @param delete the value for Supplier.Delete
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder delete(Integer delete) {
            obj.setDelete(delete);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Supplier
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Supplier build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table Supplier
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("Id"),
        name("Name"),
        phone("Phone"),
        address("Address"),
        comment("Comment"),
        delete("Delete");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table Supplier
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Supplier
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Supplier
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Supplier
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Supplier
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Supplier
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}