package com.ximuyi.demo.mybatis.mapper;

import com.ximuyi.demo.mybatis.model.Idgen;
import com.ximuyi.demo.mybatis.model.IdgenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IdgenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IdGen
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    long countByExample(IdgenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IdGen
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    int deleteByExample(IdgenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IdGen
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    int insert(Idgen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IdGen
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    int insertSelective(Idgen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IdGen
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    List<Idgen> selectByExample(IdgenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IdGen
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    int updateByExampleSelective(@Param("record") Idgen record, @Param("example") IdgenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IdGen
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    int updateByExample(@Param("record") Idgen record, @Param("example") IdgenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IdGen
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Idgen selectOneByExample(IdgenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IdGen
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<Idgen> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IdGen
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<Idgen> list, @Param("selective") Idgen.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IdGen
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(Idgen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IdGen
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(Idgen record);
}