package com.ximuyi.demo.mybatis.mapper;

import com.ximuyi.demo.mybatis.model.Optimize;
import com.ximuyi.demo.mybatis.model.OptimizeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OptimizeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Optimize
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    long countByExample(OptimizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Optimize
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    int deleteByExample(OptimizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Optimize
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    int insert(Optimize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Optimize
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    int insertSelective(Optimize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Optimize
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    List<Optimize> selectByExample(OptimizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Optimize
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    int updateByExampleSelective(@Param("record") Optimize record, @Param("example") OptimizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Optimize
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    int updateByExample(@Param("record") Optimize record, @Param("example") OptimizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Optimize
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Optimize selectOneByExample(OptimizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Optimize
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<Optimize> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Optimize
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<Optimize> list, @Param("selective") Optimize.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Optimize
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(Optimize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Optimize
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(Optimize record);
}