package com.ximuyi.demo.mybatis.mapper;

import com.ximuyi.demo.mybatis.model.Stock;
import com.ximuyi.demo.mybatis.model.StockExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Stock
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    long countByExample(StockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Stock
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    int deleteByExample(StockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Stock
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    int insert(Stock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Stock
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    int insertSelective(Stock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Stock
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    List<Stock> selectByExample(StockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Stock
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    int updateByExampleSelective(@Param("record") Stock record, @Param("example") StockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Stock
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    int updateByExample(@Param("record") Stock record, @Param("example") StockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Stock
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Stock selectOneByExample(StockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Stock
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<Stock> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Stock
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<Stock> list, @Param("selective") Stock.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Stock
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(Stock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Stock
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(Stock record);
}