package com.jim.demo.mybatis.model;

import java.io.Serializable;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

public class Goods implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Goods.Id
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Goods.Name
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Goods.Goods
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private Long goods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Goods.GoodsDelete
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private String goodsdelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Goods.Approach
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private String approach;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Goods.User
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private String user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Goods.Order
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private Long order;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Goods.Date
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Goods.Num
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Goods.Price
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Goods.Amount
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private Double amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Goods.Comment
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Goods.Delete
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private Integer delete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Goods
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private Map<String, Boolean> selectiveColumns = new HashMap<String, Boolean>();

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Goods.Id
     *
     * @return the value of Goods.Id
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Goods.Id
     *
     * @param id the value for Goods.Id
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Goods.Name
     *
     * @return the value of Goods.Name
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Goods.Name
     *
     * @param name the value for Goods.Name
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Goods.Goods
     *
     * @return the value of Goods.Goods
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public Long getGoods() {
        return goods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Goods.Goods
     *
     * @param goods the value for Goods.Goods
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setGoods(Long goods) {
        this.goods = goods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Goods.GoodsDelete
     *
     * @return the value of Goods.GoodsDelete
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public String getGoodsdelete() {
        return goodsdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Goods.GoodsDelete
     *
     * @param goodsdelete the value for Goods.GoodsDelete
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setGoodsdelete(String goodsdelete) {
        this.goodsdelete = goodsdelete == null ? null : goodsdelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Goods.Approach
     *
     * @return the value of Goods.Approach
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public String getApproach() {
        return approach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Goods.Approach
     *
     * @param approach the value for Goods.Approach
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setApproach(String approach) {
        this.approach = approach == null ? null : approach.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Goods.User
     *
     * @return the value of Goods.User
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Goods.User
     *
     * @param user the value for Goods.User
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Goods.Order
     *
     * @return the value of Goods.Order
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public Long getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Goods.Order
     *
     * @param order the value for Goods.Order
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setOrder(Long order) {
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Goods.Date
     *
     * @return the value of Goods.Date
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Goods.Date
     *
     * @param date the value for Goods.Date
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Goods.Num
     *
     * @return the value of Goods.Num
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Goods.Num
     *
     * @param num the value for Goods.Num
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Goods.Price
     *
     * @return the value of Goods.Price
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Goods.Price
     *
     * @param price the value for Goods.Price
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Goods.Amount
     *
     * @return the value of Goods.Amount
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Goods.Amount
     *
     * @param amount the value for Goods.Amount
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Goods.Comment
     *
     * @return the value of Goods.Comment
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Goods.Comment
     *
     * @param comment the value for Goods.Comment
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Goods.Delete
     *
     * @return the value of Goods.Delete
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public Integer getDelete() {
        return delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Goods.Delete
     *
     * @param delete the value for Goods.Delete
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setDelete(Integer delete) {
        this.delete = delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static Goods.Builder builder() {
        return new Goods.Builder();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public boolean hasSelective() {
        return this.selectiveColumns.size() > 0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public boolean hasSelective(String column) {
        return this.selectiveColumns.get(column) != null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Goods selective(Column ... columns) {
        this.selectiveColumns.clear();
        if (columns != null) {
            for (Column column : columns) {
                this.selectiveColumns.put(column.value(), true);
            }
        }
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table Goods
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private Goods obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Goods
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new Goods();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Goods.Id
         *
         * @param id the value for Goods.Id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder id(Long id) {
            obj.setId(id);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Goods.Name
         *
         * @param name the value for Goods.Name
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder name(String name) {
            obj.setName(name);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Goods.Goods
         *
         * @param goods the value for Goods.Goods
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder goods(Long goods) {
            obj.setGoods(goods);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Goods.GoodsDelete
         *
         * @param goodsdelete the value for Goods.GoodsDelete
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder goodsdelete(String goodsdelete) {
            obj.setGoodsdelete(goodsdelete);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Goods.Approach
         *
         * @param approach the value for Goods.Approach
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder approach(String approach) {
            obj.setApproach(approach);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Goods.User
         *
         * @param user the value for Goods.User
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder user(String user) {
            obj.setUser(user);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Goods.Order
         *
         * @param order the value for Goods.Order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder order(Long order) {
            obj.setOrder(order);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Goods.Date
         *
         * @param date the value for Goods.Date
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder date(Date date) {
            obj.setDate(date);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Goods.Num
         *
         * @param num the value for Goods.Num
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder num(Integer num) {
            obj.setNum(num);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Goods.Price
         *
         * @param price the value for Goods.Price
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder price(Double price) {
            obj.setPrice(price);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Goods.Amount
         *
         * @param amount the value for Goods.Amount
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder amount(Double amount) {
            obj.setAmount(amount);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Goods.Comment
         *
         * @param comment the value for Goods.Comment
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder comment(String comment) {
            obj.setComment(comment);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Goods.Delete
         *
         * @param delete the value for Goods.Delete
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder delete(Integer delete) {
            obj.setDelete(delete);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Goods
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Goods build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table Goods
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("Id"),
        name("Name"),
        goods("Goods"),
        goodsdelete("GoodsDelete"),
        approach("Approach"),
        user("User"),
        order("Order"),
        date("Date"),
        num("Num"),
        price("Price"),
        amount("Amount"),
        comment("Comment"),
        delete("Delete");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table Goods
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Goods
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Goods
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Goods
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Goods
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Goods
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}