package com.jim.demo.mybatis.model;

import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;

public class Optimize implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Optimize.Id
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Optimize.Key1
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private Integer key1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Optimize.Key2
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private Integer key2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Optimize.Value
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Optimize
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Optimize
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    private Map<String, Boolean> selectiveColumns = new HashMap<String, Boolean>();

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Optimize.Id
     *
     * @return the value of Optimize.Id
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Optimize.Id
     *
     * @param id the value for Optimize.Id
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Optimize.Key1
     *
     * @return the value of Optimize.Key1
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public Integer getKey1() {
        return key1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Optimize.Key1
     *
     * @param key1 the value for Optimize.Key1
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setKey1(Integer key1) {
        this.key1 = key1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Optimize.Key2
     *
     * @return the value of Optimize.Key2
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public Integer getKey2() {
        return key2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Optimize.Key2
     *
     * @param key2 the value for Optimize.Key2
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setKey2(Integer key2) {
        this.key2 = key2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Optimize.Value
     *
     * @return the value of Optimize.Value
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Optimize.Value
     *
     * @param value the value for Optimize.Value
     *
     * @mbg.generated Wed Apr 18 16:08:01 CST 2018
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Optimize
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static Optimize.Builder builder() {
        return new Optimize.Builder();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Optimize
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public boolean hasSelective() {
        return this.selectiveColumns.size() > 0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Optimize
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public boolean hasSelective(String column) {
        return this.selectiveColumns.get(column) != null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Optimize
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Optimize selective(Column ... columns) {
        this.selectiveColumns.clear();
        if (columns != null) {
            for (Column column : columns) {
                this.selectiveColumns.put(column.value(), true);
            }
        }
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Optimize
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table Optimize
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private Optimize obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Optimize
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder() {
            this.obj = new Optimize();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Optimize.Id
         *
         * @param id the value for Optimize.Id
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder id(Long id) {
            obj.setId(id);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Optimize.Key1
         *
         * @param key1 the value for Optimize.Key1
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder key1(Integer key1) {
            obj.setKey1(key1);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Optimize.Key2
         *
         * @param key2 the value for Optimize.Key2
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder key2(Integer key2) {
            obj.setKey2(key2);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column Optimize.Value
         *
         * @param value the value for Optimize.Value
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Builder value(String value) {
            obj.setValue(value);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Optimize
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Optimize build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table Optimize
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("Id"),
        key1("Key1"),
        key2("Key2"),
        value("Value");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table Optimize
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Optimize
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Optimize
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Optimize
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Optimize
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table Optimize
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}